### ISSUE TITLE
已经不能正常使用了

### ISSUE THREAD

**Issue by csbde** [coldnight/magpie#1]
请问还有更新计划吗？ 比较需要这功能

```
 150805 16:38:57 client:201] -- Connected, start connect WebQQ..
[I 150805 16:38:57 requests:46] 获取 login_sig...
[I 150805 16:38:57 requests:64] 获取Login Sig: 
[E 150805 16:38:57 ioloop:612] Exception in callback <functools.partial object at 0x7f1b9b1859f0>
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/tornado-4.2.1-py2.7-linux-x86_64.egg/tornado/ioloop.py", line 592, in _run_callback
        ret = callback()
      File "/usr/lib/python2.7/site-packages/tornado-4.2.1-py2.7-linux-x86_64.egg/tornado/stack_context.py", line 343, in wrapped
        raise_exc_info(exc)
      File "/usr/lib/python2.7/site-packages/tornado-4.2.1-py2.7-linux-x86_64.egg/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "build/bdist.linux-x86_64/egg/twqq/hub.py", line 488, in _wrap
        func(resp, data, *args, **kwargs)
      File "build/bdist.linux-x86_64/egg/twqq/requests.py", line 84, in callback
        r, vcode, uin = eval("self.hub." + data.strip().rstrip(";"))
      File "<string>", line 1, in <module>
    TypeError: <lambda>() takes exactly 3 arguments (4 given)
```

**Comment by coldnight** [comment]
抱歉, 主要由于工作很忙, 私事又多加上此前腾讯宣布放弃 WebQQ 业务导致 twqq 库年久失修, 所以不敢保证有更新计划. 另外推荐一个项目: https://github.com/xiehuc/pidgin-lwqq

**Comment by csbde** [comment]
了解了，谢谢
